package net.java21.crowfoot.database.edit;

import net.java21.crowfoot.database.client.dto.ConnectionAccess;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 * 행 편집 계약 — PostgreSQL 실물(지정 스키마 {@code shop}). docker 데몬이 없으면 스킵한다.
 */
@Testcontainers(disabledWithoutDocker = true)
class EditPostgresTest extends EditContractTest {

    @Container
    private static final PostgreSQLContainer POSTGRES = new PostgreSQLContainer("postgres:16-alpine")
            .withDatabaseName("app").withUsername("crowfoot").withPassword("test-pass-1");

    @Override
    Connection direct() throws Exception {
        Connection connection = DriverManager.getConnection(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE SCHEMA IF NOT EXISTS shop");
            statement.execute("SET search_path TO shop");
        }
        return connection;
    }

    @Override
    void resetData() throws Exception {
        try (Connection connection = direct(); Statement statement = connection.createStatement()) {
            statement.execute("DROP VIEW IF EXISTS done_notes");
            statement.execute("DROP TABLE IF EXISTS tags");
            statement.execute("DROP TABLE IF EXISTS note_logs");
            statement.execute("DROP TABLE IF EXISTS notes");
            statement.execute("""
                    CREATE TABLE notes (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(50) NOT NULL,
                      body TEXT NULL,
                      done BOOLEAN NOT NULL DEFAULT FALSE,
                      qty INT NULL,
                      attachment BYTEA NULL
                    )""");
            statement.execute("CREATE TABLE tags (note_id BIGINT NOT NULL, tag VARCHAR(30) NOT NULL, weight INT NULL, PRIMARY KEY (note_id, tag))");
            statement.execute("CREATE TABLE note_logs (message VARCHAR(100))");
            statement.execute("CREATE VIEW done_notes AS SELECT id, title FROM notes WHERE done");
            statement.execute("INSERT INTO notes (id, title, body, done, qty) VALUES (1, '첫 메모', '" + longText() + "', FALSE, 10), (2, '둘째 메모', '본문 2', FALSE, NULL)");
            statement.execute("ALTER TABLE notes ALTER COLUMN id RESTART WITH 3");
            statement.execute("INSERT INTO tags VALUES (1, 'work', 1), (2, 'home', NULL)");
        }
    }

    @Override
    ConnectionAccess access() {
        return new ConnectionAccess(CONNECTION, "개발 PG", WORKSPACE, "EDITOR", "postgresql",
                POSTGRES.getHost(), POSTGRES.getMappedPort(5432), "app", "shop", "crowfoot", "test-pass-1");
    }

    @Override
    String falseLiteral() {
        return "FALSE";
    }

    @Override
    String trueLiteral() {
        return "TRUE";
    }
}
